#!/bin/bash

if [ -z "$ETCD_URL" ]
then
  echo "ETCD_URL must be set"
  exit 1
fi

if [[ $1 == "--recursive" ]]
  then
  RECURSIVE="&recursive=true"
  shift
fi

KEY=$1

curl -s -L ${ETCD_URL}/v2/keys/${KEY}?wait=true${RECURSIVE}
