#!/bin/bash
set -e

PID_FILE="/var/log/lokalebasen-service-discovery.pid"

if [[ -e "$PID_FILE" ]]
  then
  exit 0
fi

echo "$$" > $PID_FILE
trap "rm $PID_FILE" INT TERM EXIT


etcdwatch --recursive sites-enabled/
SITES="`etcdget sites-enabled/ | jq -r '.node.nodes[].value' | grep -v null`"

for SITE in $SITES
do
  update-site $SITE 2>&1 >> $OUTPUT
done

echo "Reloading nginx..." >> $OUTPUT

nginx -t >> $OUTPUT

nginx -t && nginx -s reload
