#!/bin/bash
set -e

if [[ "$1" == "--force" ]]
  then
  FORCE=$1
  SITE=$2
else
  SITE=$1
fi


if [ -z "$FORCE" ]
  then
  etcdwatch $SITE/current_revision
fi

new-upstream-config ${SITE} > /etc/nginx/site-includes/${SITE}.upstream

echo Reloading nginx... > $OUTPUT
kill -HUP `cat /run/nginx.pid`
